// <auto-generated />
namespace Tlahui.Context.WebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class BoolDisplayTypeAnnotation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BoolDisplayTypeAnnotation));
        
        string IMigrationMetadata.Id
        {
            get { return "201806271605591_BoolDisplayTypeAnnotation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
